export const ROOT = "ROOT";

/**
 * AUTHENTICATION
 * 
 */


export const USER_REGISTRATION = "USER_REGISTRATION"
export const USER_LOGIN = "USER_LOGIN"
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED"
export const LOGIN_REQUEST_SUCCESSFULL= "LOGIN_REQUEST_SUCCESSFULL"
export const LOGIN_REQUEST_INITIATED= "LOGIN_REQUEST_INITIATED"
export const LOGOUT_FAILED = "LOGOUT_FAILED"
export const LOGOUT_SUCCESSFULL = "LOGOUT_SUCCESSFULL"
export const FETCH_USER_ERROR = "FETCH_USER_ERROR"
export const Fecth_USER_SUCCESS = "Fecth_USER_SUCCESS"
export const FETCH_USER_INITIATED = "FETCH_USER_INITIATED"
export const FETCH_SMS_HISTORY_INITIATED = "FETCH_SMS_HISTORY_INITIATED"
export const FETCH_SMS_HISTORY_ERROR = "FETCH_SMS_HISTORY_ERROR"
export const FETCH_SMS_HISTORY_SUCCESSFUL = "FETCH_SMS_HISTORY_SUCCESSFUL"
export const FETCH_SMS_SCHEDULE_INITIATED = "FETCH_SMS_SCHEDULE_INITIATED"
export const FETCH_SMS_SCHEDULE_ERROR = "FETCH_SMS_SCHEDULE_ERROR"
export const FETCH_SMS_SCHEDULE_SUCCESSFULL = "FETCH_SMS_SCHEDULE_SUCCESSFULL"
export const FETCH_SMS_BALANCE_INITIATED = "FETCH_SMS_BALANCE_INITIATED"
export const FETCH_SMS_BALANCE_ERROR = "FETCH_SMS_BALANCE_ERROR"
export const FETCH_SMS_BALANCE_SUCCESSFULL = "FETCH_SMS_BALANCE_SUCCESSFULL"


